wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.0
    start_time: 1672667854.986812
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.0
      5: 0.13.7
      8:
      - 5
